version: "3.7"
services:
  # postgres:
  #   image: postgres:12
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes: 
  #     - pgdata:/var/lib/postgres/data

  # NOTE: svn and api must be able to share the svndata volume R/W. On kubernetes this
  # usually requires running both containers on the same Deployment/Pod. It is important
  # to make sure there is a enough CPU available to avoid a bottleneck.

  svn:
    image: kruxia/svn:alpine
    environment:
      SERVER_ADMIN: ${SERVER_ADMIN}
      SERVER_NAME: ${ARCHIVE_URL}
    volumes:
      - svndata:/var/svn

  api:
    image: ark_api
    depends_on:
      # - postgres
      - svn
    environment:
      ARCHIVE_FILES: /var/svn
      ARCHIVE_SERVER: http://svn
      ARCHIVE_URL: ${ARCHIVE_URL}
      # DATABASE_NAME: ${POSTGRES_DB}
      # DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - svndata:/var/svn
      - ./api:/var/api

  ui: 
    image: ark_ui
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ui/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./ui/ssl:/etc/nginx/ssl

volumes:
  # pgdata:
  svndata: