services:
  # ark:
  #   build:
  #     context: ./
  #     dockerfile: ark/Dockerfile
  #   environment:
  #     RUST_BACKTRACE: '1'
  #     TRACING_LEVEL: 'INFO'
  #     DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/ark'
  #     AWS_ACCESS_KEY_ID: 'minioadmin'
  #     AWS_SECRET_ACCESS_KEY: 'minioadmin'
  #     AWS_REGION: 'us-east-1'
  #     S3_ENDPOINT_URL: 'http://minio:9000/'
  #   ports:
  #     - '8000:8000'

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-26T22-10-45Z
    command: ["server", "/data", "--console-address", ":9001"]
    environment: {}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - miniodata:/data

volumes:
  miniodata:
  pgdata:
