version: "3.7"
services:
  svn:
    image: kruxia/svn:alpine
    environment:
      SERVER_ADMIN: $SERVER_ADMIN
      SERVER_NAME: svn
    ports:
      - "7000:80"
    volumes:
      # - svndata:/var/svn
      - ./svndata:/var/svn

  # postgres:
  #   image: postgres:12
  #   environment:
  #     POSTGRES_DATABASE: ark
  #     POSTGRES_USERNAME: ark
  #     POSTGRES_PASSWORD: ark
  #   ports:
  #     - "5433:5432"
  #   volumes: 
  #     - pgdata:/var/lib/postgres/data

  # api:
  #   build: ./api
  #   depends_on:
  #     - postgres
  #     - svn
  #   environment:
  #     POSTGRES_URL: postgres://ark:ark@localhost:5433/ark
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - /var/api/target
  #     - svndata:/var/svn
  #     - ./api:/var/api

# volumes:
#   svndata:
#   pgdata: