version: "3.7"
services:
  svn:
    build: ./svn
    environment:
      ARCHIVE_FILES: /var/svn
      SERVER_ADMIN: $SERVER_ADMIN
      SERVER_NAME: $SERVER_NAME
    ports:
      - "7000:80"
    volumes:
      - svndata:/var/svn
      - ./svn:/var/ark/svn

  db:
    build: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./db:/var/db

  api:
    build: ./ark
    depends_on:
      - db
      - svn
    environment:
      ARCHIVE_FILES: /var/svn
      ARCHIVE_SERVER: http://svn/svn/
      ARCHIVE_URL: http://localhost:7000/svn/
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - svndata:/var/svn
      - ./ark:/var/ark

volumes:
  pgdata:
  svndata: