version: "3.7"
services:
  svn:
    image: kruxia/svn:alpine
    environment:
      SERVER_ADMIN: $SERVER_ADMIN
      SERVER_NAME: svn
    ports:
      - "7000:80"
    volumes:
      - svndata:/var/svn

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ark
      POSTGRES_USER: ark
      POSTGRES_PASSWORD: ark
    volumes: 
      - pgdata:/var/lib/postgres/data

  api:
    # image: kruxia/ark-api
    # build: ./api
    build: ./apipy
    depends_on:
      - postgres
      - svn
    environment:
      ARCHIVE_FILES: /var/svn
      ARCHIVE_SERVER: http://svn
      DATABASE_NAME: ark
      DATABASE_URL: postgres://ark:ark@postgres:5432/${DATABASE_NAME}
    ports:
      - "8000:8000"
    volumes:
      - svndata:/var/svn
      - /var/api/target
      # - ./api:/var/api
      - ./apipy:/var/api

volumes:
  pgdata:
  svndata: