version: "3.7"
services:
  svn:
    image: kruxia/svn:alpine
    environment:
      SERVER_ADMIN: $SERVER_ADMIN
      SERVER_NAME: svn
    ports:
      - "7000:80"
    volumes:
      - svndata:/var/svn

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ark
      POSTGRES_USER: ark
      POSTGRES_PASSWORD: ark
    volumes: 
      - pgdata:/var/lib/postgres/data

  api:
    build: ./api
    depends_on:
      - postgres
      - svn
    environment:
      ARCHIVE_FILES: /var/svn
      ARCHIVE_SERVER: http://svn
      ARCHIVE_URL: http://localhost:7000
      DATABASE_NAME: ark
      DATABASE_URL: postgres://ark:ark@postgres:5432/ark
    ports:
      - "8000:8000"
    volumes:
      - svndata:/var/svn
      - ./api:/var/api

  ui: 
    build:
      context: ./ui
      dockerfile: deploy.Dockerfile
      args:
        API_URL: http://localhost:8000
        ARCHIVE_URL: http://localhost:7000
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  pgdata:
  svndata: