version: "3.7"
services:
  svn:
    image: kruxia/svn:alpine
    environment:
      SERVER_ADMIN: $SERVER_ADMIN
      SERVER_NAME: svn
    ports:
      - "7000:80"
    volumes:
      - svndata:/var/svn

  api:
    build: ./api
    ports:
      - "8000:80"
    volumes:
      - svndata:/var/svn

volumes:
  svndata: