version: "3.7"
services:
  svn:
    image: kruxia/svn:alpine
    environment:
      SERVER_ADMIN: $SERVER_ADMIN
      SERVER_NAME: svn
    ports:
      - "7000:80"
    volumes:
      - svndata:/var/svn

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ark
      POSTGRES_USER: ark
      POSTGRES_PASSWORD: ark
    volumes: 
      - pgdata:/var/lib/postgres/data

  api:
    build: ./api
    depends_on:
      - postgres
      - svn
    environment:
      ARCHIVE_FILES: /var/svn
      ARCHIVE_SERVER: http://svn
      ARCHIVE_URL: ${ARCHIVE_URL}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - svndata:/var/svn
      - ./api:/var/api

volumes:
  pgdata:
  svndata: