version: "3.7"
services:
  svn:
    build: ./svn
    environment:
      SERVER_ADMIN: $SERVER_ADMIN
      SERVER_NAME: svn
    ports:
      - "7000:80"
    volumes:
      - svndata:/var/svn

  app:
    build: ./app
    ports:
      - "8000:80"
    volumes:
      - svndata:/var/svn

volumes:
  svndata: