#!/bin/bash

TEST_DATABASE=${DATABASE_NAME}_test
psql -e -q -c "DROP DATABASE IF EXISTS ${TEST_DATABASE}" $DATABASE_URL
psql -e -q -c "CREATE DATABASE ${TEST_DATABASE}" $DATABASE_URL
export DATABASE_NAME=${TEST_DATABASE}
export DATABASE_URL=${DATABASE_URL}_test

pytest $@
